# Generated by Django 5.2.10 on 2026-01-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_score',
            field=models.CharField(blank=True, choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Fair'), ('D', 'D - Poor'), ('E', 'E - Very Poor')], max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
